/**
 * Lista oficial de discursos públicos (número + tema).
 */
const discursos = [
  { numero: 1, tema: "Você conhece bem a Deus?" },
  { numero: 2, tema: "Você vai sobreviver aos últimos dias?" },
  { numero: 3, tema: "Você está avançando com a organização unida de Jeová?" },
  { numero: 4, tema: "Que provas temos de que Deus existe?" },
  { numero: 5, tema: "Você pode ter uma família feliz!" },
  { numero: 6, tema: "O dilúvio dos dias de Noé e você" },
  { numero: 7, tema: "Imite a misericórdia de Jeová" },
  { numero: 8, tema: "Viva para fazer a vontade de Deus" },
  { numero: 9, tema: "Escute e faça o que a Bíblia diz" },
  { numero: 10, tema: "Seja honesto em tudo" },
  { numero: 11, tema: "Imite a Jesus e não faça parte do mundo" },
  { numero: 12, tema: "Deus quer que você respeite quem tem autoridade" },
  { numero: 13, tema: "Qual o ponto de vista de Deus sobre o sexo e o casamento?" },
  { numero: 14, tema: "Um povo puro e limpo honra a Jeová" },
  { numero: 15, tema: "‘Faça o bem a todos’" },
  { numero: 16, tema: "Seja cada vez mais amigo de Jeová" },
  { numero: 17, tema: "Glorifique a Deus com tudo o que você tem" },
  { numero: 18, tema: "Faça de Jeová a sua fortaleza" },
  { numero: 19, tema: "Como você pode saber seu futuro?" },
  { numero: 20, tema: "Chegou o tempo de Deus governar o mundo?" },
  { numero: 21, tema: "Dê valor ao seu lugar no Reino de Deus" },
  { numero: 22, tema: "Você está usando bem o que Jeová lhe dá?" },
  { numero: 23, tema: "A vida tem objetivo" },
  { numero: 24, tema: "Você encontrou “uma pérola de grande valor”?" },
  { numero: 25, tema: "Lute contra o espírito do mundo" },
  { numero: 26, tema: "Você é importante para Deus?" },
  { numero: 27, tema: "Como construir um casamento feliz" },
  { numero: 28, tema: "Mostre respeito e amor no seu casamento" },
  { numero: 29, tema: "As responsabilidades e recompensas de ter filhos" },
  { numero: 30, tema: "Como melhorar a comunicação na família" },
  { numero: 31, tema: "Você tem consciência da sua necessidade espiritual?" },
  { numero: 32, tema: "Como lidar com as ansiedades da vida" },
  { numero: 33, tema: "Quando vai existir verdadeira justiça?" },
  { numero: 34, tema: "Você vai ser marcado para sobreviver?" },
  { numero: 35, tema: "É possível viver para sempre? O que você precisa fazer?" },
  { numero: 36, tema: "Será que a vida é só isso?" },
  { numero: 37, tema: "Obedecer a Deus é mesmo a melhor coisa a fazer?" },
  { numero: 38, tema: "Como você pode sobreviver ao fim do mundo?" },
  { numero: 39, tema: "Jesus Cristo vence o mundo — Como e quando?" },
  { numero: 40, tema: "O que vai acontecer em breve?" },
  { numero: 41, tema: "Fiquem parados e vejam como Jeová os salvará" },
  { numero: 42, tema: "O amor pode vencer o ódio?" },
  { numero: 43, tema: "Tudo o que Deus nos pede é para o nosso bem" },
  { numero: 44, tema: "Como os ensinos de Jesus podem ajudar você?" },
  { numero: 45, tema: "Continue andando no caminho que leva à vida" },
  { numero: 46, tema: "Fortaleça sua confiança em Jeová" },
  { numero: 47, tema: "‘Tenha fé nas boas novas’" },
  { numero: 48, tema: "Seja leal a Deus mesmo quando for testado" },
  { numero: 49, tema: "Será que um dia a Terra vai ser limpa?" },
  { numero: 50, tema: "Como sempre tomar as melhores decisões" },
  { numero: 51, tema: "Será que a verdade da Bíblia está mudando a sua vida?" },
  { numero: 52, tema: "Quem é o seu Deus?" },
  { numero: 53, tema: "Você pensa como Deus?" },
  { numero: 54, tema: "Fortaleça sua fé em Deus e em suas promessas" },
  { numero: 55, tema: "Você está fazendo um bom nome perante Deus?" },
  { numero: 56, tema: "Existe um líder em quem você pode confiar?" },
  { numero: 57, tema: "Como suportar perseguição" },
  { numero: 58, tema: "Quem são os verdadeiros seguidores de Cristo?" },
  { numero: 59, tema: "Ceifará o que semear" },
  { numero: 60, tema: "Você tem um objetivo na vida?" },
  { numero: 61, tema: "Nas promessas de quem você confia?" },
  { numero: 62, tema: "Onde encontrar uma esperança real para o futuro?" },
  { numero: 63, tema: "É possível encontrar a verdade?" },
  { numero: 64, tema: "Você ama os prazeres ou a Deus?" },
  { numero: 65, tema: "Como podemos ser pacíficos num mundo cheio de ódio" },
  { numero: 66, tema: "Você também vai participar na colheita?" },
  { numero: 67, tema: "Medite na Bíblia e nas criações de Jeová" },
  { numero: 68, tema: "‘Continuem a perdoar uns aos outros liberalmente’" },
  { numero: 69, tema: "Por que mostrar amor abnegado?" },
  { numero: 70, tema: "Por que Deus merece sua confiança?" },
  { numero: 71, tema: "‘Mantenha-se desperto’ — Por que e como?" },
  { numero: 72, tema: "O amor identifica os cristãos verdadeiros" },
  { numero: 73, tema: "Você tem “um coração sábio”?" },
  { numero: 74, tema: "Os olhos de Jeová estão em todo lugar" },
  { numero: 75, tema: "Mostre que você apoia o direito de Jeová governar" },
  { numero: 76, tema: "Princípios bíblicos — Podem nos ajudar a lidar com os problemas atuais?" },
  { numero: 77, tema: "“Sempre mostrem hospitalidade”" },
  { numero: 78, tema: "Sirva a Jeová com um coração alegre" },
  { numero: 79, tema: "Você vai escolher ser amigo de Deus?" },
  { numero: 80, tema: "Você baseia sua esperança na ciência ou na Bíblia?" },
  { numero: 81, tema: "Quem está qualificado para fazer discípulos?" },
  { numero: 82, tema: "Jeová e Cristo fazem parte de uma trindade?" },
  { numero: 83, tema: "Será que os cristãos precisam obedecer aos Dez Mandamentos?" },
  { numero: 84, tema: "Escapará do destino deste mundo?" },
  { numero: 85, tema: "Boas notícias num mundo violento" },
  { numero: 86, tema: "Como orar a Deus e ser ouvido por ele?" },
  { numero: 87, tema: "Qual é a sua relação com Deus?" },
  { numero: 88, tema: "Por que viver de acordo com os padrões da Bíblia?" },
  { numero: 89, tema: "Quem tem sede da verdade, venha!" },
  { numero: 90, tema: "Faça o máximo para alcançar a verdadeira vida!" },
  { numero: 91, tema: "A presença do Messias e seu domínio" },
  { numero: 92, tema: "O papel da religião nos assuntos do mundo" },
  { numero: 93, tema: "Desastres naturais — Quando vão acabar?" },
  { numero: 94, tema: "A religião verdadeira atende às necessidades da sociedade humana" },
  { numero: 95, tema: "Não seja enganado pelo ocultismo!" },
  { numero: 96, tema: "O que vai acontecer com as religiões?" },
  { numero: 97, tema: "Permaneçamos inculpes em meio a uma geração pervertida" },
  { numero: 98, tema: "“A cena deste mundo está mudando”" },
  { numero: 99, tema: "Por que podemos confiar no que a Bíblia diz?" },
  { numero: 100, tema: "Como fazer amizades fortes e verdadeiras" },
  { numero: 101, tema: "Jeová é o “Grandioso Criador”" },
  { numero: 102, tema: "Preste atenção à “palavra profética”" },
  { numero: 103, tema: "Como você pode ter a verdadeira alegria?" },
  { numero: 104, tema: "Pais, vocês estão construindo com materiais à prova de fogo?" },
  { numero: 105, tema: "Somos consolados em todas as nossas tribulações" },
  { numero: 106, tema: "Arruinar a terra provocará retribuição divina" },
  { numero: 107, tema: "Você está treinando bem a sua consciência?" },
  { numero: 108, tema: "Você pode encarar o futuro com confiança!" },
  { numero: 109, tema: "O Reino de Deus está próximo" },
  { numero: 110, tema: "Deus vem primeiro na vida familiar bem-sucedida" },
  { numero: 111, tema: "É possível que a humanidade seja completamente curada?" },
  { numero: 112, tema: "Como mostrar amor num mundo egoísta" },
  { numero: 113, tema: "Jovens - Como vocês podem ter uma vida feliz?" },
  { numero: 114, tema: "Apreço pelas maravilhas da criação de Deus" },
  { numero: 115, tema: "Não caia nas armadilhas de Satanás" },
  { numero: 116, tema: "Escolha sabiamente com quem irá associar-se!" },
  { numero: 117, tema: "Como vencer o mal com o bem" },
  { numero: 118, tema: "Olhemos os jovens do ponto de vista de Jeová" },
  { numero: 119, tema: "Por que é benéfico que os cristãos vivam separados do mundo" },
  { numero: 120, tema: "Por que se submeter à regência de Deus agora" },
  { numero: 121, tema: "Uma família mundial que será salva da destruição" },
  { numero: 122, tema: "Paz global — de onde virá?" },
  { numero: 123, tema: "Por que os cristãos têm de ser diferentes" },
  { numero: 124, tema: "Razões para crer que a Bíblia é de autoria divina" },
  { numero: 125, tema: "Por que a humanidade precisa de resgate" },
  { numero: 126, tema: "Quem se salvará?" },
  { numero: 127, tema: "O que acontece quando morremos?" },
  { numero: 128, tema: "É o inferno um lugar de tormento ardente?" },
  { numero: 129, tema: "O que a Bíblia diz sobre a Trindade?" },
  { numero: 130, tema: "A terra permanecerá para sempre" },
  { numero: 131, tema: "Tome posição contra o Diabo!" },
  { numero: 132, tema: "Ressurreição — A vitória sobre a morte!" },
  { numero: 133, tema: "Tem importância o que cremos sobre a nossa origem?" },
  { numero: 134, tema: "Será que os cristãos precisam guardar o sábado?" },
  { numero: 135, tema: "A santidade da vida e do sangue" },
  { numero: 136, tema: "Será que Deus aprova o uso de imagens na adoração?" },
  { numero: 137, tema: "Ocorreram realmente os milagres da Bíblia?" },
  { numero: 138, tema: "Viva com bom juízo num mundo depravado" },
  { numero: 139, tema: "Sabedoria divina num mundo científico" },
  { numero: 140, tema: "Quem é realmente Jesus Cristo?" },
  { numero: 141, tema: "Quando terão fim os gemidos da criação humana?" },
  { numero: 142, tema: "Por que refugiar-se em Jeová" },
  { numero: 143, tema: "Confie no Deus de todo consolo" },
  { numero: 144, tema: "Uma congregação leal sob a liderança de Cristo" },
  { numero: 145, tema: "Quem é semelhante a Jeová, nosso Deus?" },
  { numero: 146, tema: "Use a educação para louvar a Jeová" },
  { numero: 147, tema: "Confie que Jeová tem o poder para nos salvar" },
  { numero: 148, tema: "Você tem o mesmo conceito de Deus sobre a vida?" },
  { numero: 149, tema: "O que significa “andar com Deus”?" },
  { numero: 150, tema: "Este mundo está condenado à destruição?" },
  { numero: 151, tema: "Jeová é “uma altura protetora” para seu povo" },
  { numero: 152, tema: "Armagedom — por que e quando?" },
  { numero: 153, tema: "Tenha bem em mente o “atemorizante dia”!" },
  { numero: 154, tema: "O governo humano é pesado na balança" },
  { numero: 155, tema: "Chegou a hora do julgamento de Babilônia?" },
  { numero: 156, tema: "O Dia do Juízo — tempo de temor ou de esperança?" },
  { numero: 157, tema: "Como os verdadeiros cristãos adornam o ensino divino" },
  { numero: 158, tema: "Seja corajoso e confie em Jeová" },
  { numero: 159, tema: "Como encontrar segurança num mundo perigoso" },
  { numero: 160, tema: "Mantenha a identidade cristã!" },
  { numero: 161, tema: "Por que Jesus sofreu e morreu?" },
  { numero: 162, tema: "Seja liberto deste mundo em escuridão" },
  { numero: 163, tema: "Por que temer o Deus verdadeiro?" },
  { numero: 164, tema: "Será que Deus ainda está no controle?" },
  { numero: 165, tema: "Os valores de quem você preza?" },
  { numero: 166, tema: "Verdadeira fé — O que é e como mostrar" },
  { numero: 167, tema: "Ajamos sabiamente num mundo insensato" },
  { numero: 168, tema: "Você pode sentir-se seguro neste mundo atribulado!" },
  { numero: 169, tema: "Por que ser orientado pela Bíblia?" },
  { numero: 170, tema: "Quem está qualificado para governar a humanidade?" },
  { numero: 171, tema: "Poderá viver em paz agora — e para sempre!" },
  { numero: 172, tema: "Que reputação você tem perante Deus?" },
  { numero: 173, tema: "Existe uma religião verdadeira do ponto de vista de Deus?" },
  { numero: 174, tema: "Quem se qualificará para entrar no novo mundo de Deus?" },
  { numero: 175, tema: "O que prova que a Bíblia é autêntica?" },
  { numero: 176, tema: "Quando haverá verdadeira paz e segurança?" },
  { numero: 177, tema: "Onde encontrar ajuda em tempos de aflição?" },
  { numero: 178, tema: "Ande no caminho da integridade" },
  { numero: 179, tema: "Rejeite as fantasias do mundo, empenhe-se pelas realidades do reino" },
  { numero: 180, tema: "A Ressurreição — Por que essa esperança deve ser real para você" },
  { numero: 181, tema: "Já é mais tarde do que você imagina?" },
  { numero: 182, tema: "O que o Reino de Deus está fazendo por nós agora?" },
  { numero: 183, tema: "Desvie seus olhos do que é fútil" },
  { numero: 184, tema: "A morte é o fim de tudo?" },
  { numero: 185, tema: "Será que a verdade influencia sua vida?" },
  { numero: 186, tema: "Sirva em união com o povo feliz de Deus" },
  { numero: 187, tema: "Por que um Deus amoroso permite a maldade?" },
  { numero: 188, tema: "Você confia em Jeová?" },
  { numero: 189, tema: "Ande com Deus e receba bênçãos para sempre" },
  { numero: 190, tema: "Como se cumprirá a promessa de perfeita felicidade familiar" },
  { numero: 191, tema: "Como o amor e a fé vencem o mundo" },
  { numero: 192, tema: "Você está no caminho para a vida eterna?" },
  { numero: 193, tema: "Os problemas de hoje logo serão coisa do passado" },
  { numero: 194, tema: "Como a sabedoria de Deus nos ajuda" },
];
